name: find_duplicate_keys
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  analyzer: ^7.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
